---
services:
  frontend:
    container_name: ocv-frontend
    build: .
    restart: unless-stopped
    # depends_on:
    #   - nginx
    #   - backend-express
    environment:
      - REST_ENDPOINT=${REST_ENDPOINT} # optional
    ports:
      - '3000:3000'
    volumes: 
      - ocv-frontend:/usr/app/
    networks:
      - ocv-network

networks:
  ocv-network:
    external: true
volumes:
  ocv-frontend:
